### ISSUE TITLE
Gelöschte Dokumente können nicht wiederhergestellt werden

### ISSUE THREAD

**Issue by tgermer** [PDF-Archiver/PDF-Archive-Viewer#1]
Es wäre gut, wenn die gelöschten Dokumente in iCloud in _“Zuletzt gelöscht”_ landen würden; so könnte man diese wiederherstellen.

***
Getestet auf: iPad Pro (11 Zoll) (12.3.1); 2.0.3 (5)

**Comment by JulianKahnert** [comment]
this will be fixed in version 3.2.2 :)
