### ISSUE TITLE
Verzeichnis “1210” angelegt obwohl Jahr richtig eingestellt

### ISSUE THREAD

**Issue by tgermer** [PDF-Archiver/PDF-Archive-Viewer#3]
Es wurde das Verzeichnis `1210` Angelegt, obwohl beim Datum `2019` eingestellt war.

@JulianKahnert Hier hattest Du denke ich was verbessert im Hinblick auf das “Jahr 8”, was ich schon gemeldet hatte.

![3D32F24A-472C-47B0-83FA-EC97A80178A0](https://user-images.githubusercontent.com/21098461/61180387-c1f39180-a615-11e9-90e1-8a49535293d7.jpeg)

***
Getestet auf: iPhone 6s (12.3.1); 2.0.3 (5)

**Comment by JulianKahnert** [comment]
@tgermer kannst du die Schritte beschreiben, mit denen ich dieses Verhalten reproduzieren kann?

**Comment by tgermer** [comment]
@JulianKahnert leider nein.
Wenn es mir beim testen wieder auffällt, dann können wir den Fall ja wieder öffnen.

Wenn du auch der Meinung bist, dann schließ ihn doch.
