### ISSUE TITLE
Immer Absturz nach App-Update

### ISSUE THREAD

**Issue by tgermer** [PDF-Archiver/PDF-Archive-Viewer#4]
Nach den letzten Updates der Beta habe ich immer einen Absturz während des ersten Scans. 
Das Blatt wird erkannt und beim Sichern (Überprüfen) Absturz. 

***
Getestet auf: iPhone 6s und iPad Pro (11 Zoll) (12.3.1); 2.0.3 (5)

**Comment by tgermer** [comment]
NEIN, es passiert immer, wenn die App zurückgesetzt wurde, so sicher auch beim Update, oder wenn ich sie selber komplett geschlossen habe.

Das Dokument ist weiterhin da.

**Comment by JulianKahnert** [comment]
Kannst du das nochmal mit Version 2.0.3 (6) ausprobieren?

**Comment by tgermer** [comment]
Scheint behoben zu sein.
