### ISSUE TITLE
Absturz bei der Verarbeitung

### ISSUE THREAD

**Issue by tgermer** [PDF-Archiver/PDF-Archive-Viewer#5]
**Describe the bug**
Während der Verarbeitung stützt die App ab.

**To Reproduce**
1. Scan Dokument 1
2. Scan Dokument 2 direkt hinterher
3. Scan Dokument 3 mit einem Abstand von ca. 30 Sekunden
3. Scan Dokument 4 mit einem Abstand von ca. 30 Sekunden
4. Absturz nach klick auf "Fertig" im Scan-Überprüfen. 
Zuvor hatte ich die Auswahl des Scans noch angepasst.

**Expected behavior**
Das ich in die Ansicht der Verarbeitung komme bzw. auf den Tab 1 Scan

**Screenshots**
keine

**Smartphone information:**
 - Device: iPhone 6s & iPad Pro (11 Zoll)
 - OS: 12.3.1
 - Version 2.0.3 (6)

**Additional context**
Es ist für mich schwer nachvollziehbar, aber manchmal verschwinden auch Dokumente bei einem Absturz. Aber eher selten.

**Comment by JulianKahnert** [comment]
Sollte mit 62836ba gefixt werden.

**Comment by tgermer** [comment]
Hatte gerade wieder einen Absturz.

4 Dokument hintereinander gescannt.
Alle 4 in der Verarbeitung.
Kurz vor 100 % Absturz.
Beim nächsten öffnen der App sind noch 3 Dokumente in der Verarbeitung und das 1. fertig zum taggen.

D.h. irgendwas stimmte mit der Verarbeitungsanzeige nicht.

**Smartphone information:**
Device: iPhone 6s
OS: 12.3.1
Version 2.0.3 (7)
