### ISSUE TITLE
Das selbe Dokument ein zweites mal in der Tag Ansicht zum Benennen

### ISSUE THREAD

**Issue by tgermer** [PDF-Archiver/PDF-Archive-Viewer#6]
**Describe the bug**
Ich bekomme das selbe Dokument, welches ich zuvor schon getaggt habe, wieder zum taggen angezeigt.

**To Reproduce**
1. Dokument getaggt
2. App geschlossen (nur in den Hintergrund)
3. App geöffnet und in die Tag Ansicht
4. zuvor getaggtes Dokument wieder sichtbar; vorherige Benennung schon gesetzt (Datum, Bezeichnung, Tags)
5. Beim Speichern Hinweis: _Hier lief etwas schief! "…" konnte nicht nach  "…" bewegt werden, da bereits ein Objekt mit demselben Namen existiert._
6. Dokument über Papierkorb im Tag-Screen gelöscht.

**Expected behavior**
Das ich das nächste Dokument angezeigt bekommen

**Screenshots**

**Smartphone information:**
 - Device: iPhone 6s
 - OS: iOS 12.3.1
 - Version 2.0.3 (6)

**Additional context**
Vielleicht hat es was mit #5 zu tun.

**Comment by JulianKahnert** [comment]
Das hier kann ich leider nicht nachvollziehen. Kannst du prüfen, ob es mit Build 7 der Fehler noch auftritt?

**Comment by tgermer** [comment]
Ich kann es nicht reproduzieren. Wenn es wieder passieren sollte melde ich mich dazu in diesem Ticket.

**Comment by JulianKahnert** [comment]
Danke für die Info! Dann schließe ich das Ticket vorerst.
