### ISSUE TITLE
Dokument nicht in der Verarbeitung, obwohl im untagged Ordner

### ISSUE THREAD

**Issue by tgermer** [PDF-Archiver/PDF-Archive-Viewer#7]
**Describe the bug**
Dokument ist nicht in der Verarbeitung, obwohl es im untagged Ordner liegt.

**To Reproduce**
1. Mehre Dokumente gescannt
2. App Abgestürzt
3. App geöffnet und Dokumente getaggt
4. Ein Dokument fehlt; liegt im untagged Ordner.
`2018-04-20--PDF-ARCHIVER-TEMP-DESCRIPTION-1563172137.950038__PDFARCHIVERTEMPTAG.pdf`

**Expected behavior**
Alle gescannten Dokumente werden mir zum Taggen angeboten.

**Screenshots**
[Uploading 2018-04-20--PDF-ARCHIVER-TEMP-DESCRIPTION-1563172137.950038__PDFARCHIVERTEMPTAG.pdf…]()

**Smartphone information:**
 - Device: iPhone6
 - OS: iOS 12.3.1
 - Version 2.0.3 (6)

**Additional context**
Vielleicht hängt es mit #5 und #6 zusammen.

**Comment by JulianKahnert** [comment]
Das hier ist das erwartete Verhalten. In diesem Fall konnte die App kein Tag finden und nimmt daher den Standardtag `PDFARCHIVERTEMPTAG `. Das Tagging sollte problemlos möglich sein. Ich schließe es daher.
