### ISSUE TITLE
Absturz beim Klick auf Papierkorb im Tag-Sreen

### ISSUE THREAD

**Issue by tgermer** [PDF-Archiver/PDF-Archive-Viewer#8]
**Achtung, das war noch unter Version 2.0.3 (5)**
***
**Describe the bug**
Im Tag-Screen möchte ich ein Dokument doch nicht behalten und Klicke auf den Papierkorb, dass es gelöscht werden kann.

**To Reproduce**
1. Tag-Screen öffnen
2. Dokument löschen
3. Absturz

**Expected behavior**
Dokument wird gelöscht.

**Screenshots**
Video unter https://share.icloud.com/photos/0BQ7JenCFlNpe4xikkqdGKLag

**Smartphone information:**
 - Device: iPad Pro (11 Zoll)
 - OS: iOS 12.3.1
 - Version 2.0.3 (5)

**Additional context**
**Achtung, das war noch unter Version 2.0.3 (5)**

**Comment by JulianKahnert** [comment]
Das hier kann ich leider nicht nachvollziehen. Kannst du prüfen, ob es mit Build 7 der Fehler noch auftritt?

**Comment by tgermer** [comment]
Ja, auf dem iPad tritt es nach wie vor auf. Reproduzierbar.
Auf dem iPhone nicht.

**Comment by JulianKahnert** [comment]
Ich habe den Bug gefixt. Daher schließe ich das Issue. Falls er bei dir noch auftreten sollte - öffne es gerne wieder. 🙂
